# Generated by Django 2.2.12 on 2020-05-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('edad', models.IntegerField(default=0, verbose_name='Edad')),
                ('sexo', models.CharField(max_length=8, verbose_name='')),
                ('foto', models.BooleanField(default=False, verbose_name='Estado')),
                ('fdescrip', models.FloatField(blank=True, null=True, verbose_name='Lat')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('np_field', models.BinaryField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robot.Persona')),
            ],
        ),
    ]
