# Generated by Django 2.2.12 on 2020-05-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptor',
            old_name='pid',
            new_name='did',
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=8, verbose_name='Sexo'),
        ),
    ]
