# Generated by Django 2.2.12 on 2020-05-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20200514_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fdescrip',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
