# Generated by Django 2.2.12 on 2020-05-14 21:34

from django.db import migrations, models
import robot.models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_auto_20200514_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to=robot.models.my_awesome_upload_function),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to=robot.models.my_awesome_upload_function),
        ),
    ]
