# Generated by Django 2.2.12 on 2020-05-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20200514_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user_foto',
        ),
    ]
