# Generated by Django 2.2.12 on 2020-05-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_remove_persona_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=20, verbose_name='Producto')),
                ('cant', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Persona')),
            ],
        ),
    ]
