# Generated by Django 2.2.12 on 2020-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_aler', models.CharField(max_length=30, verbose_name='Alergia')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('fono', models.CharField(max_length=12, verbose_name='Región')),
                ('parentesco', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_nom', models.CharField(max_length=20, verbose_name='Nombre')),
                ('dosis', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('edad', models.IntegerField(default=0, verbose_name='Edad')),
                ('sexo', models.CharField(max_length=8, verbose_name='Sexo')),
                ('calle', models.CharField(max_length=40, verbose_name='Calle')),
                ('comuna', models.CharField(max_length=20, verbose_name='Comuna')),
                ('region', models.CharField(max_length=20, verbose_name='Región')),
                ('fono', models.CharField(max_length=12, verbose_name='Región')),
                ('sange', models.CharField(max_length=10, verbose_name='sange')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prev', models.CharField(max_length=30, verbose_name='Prevision')),
            ],
        ),
    ]
