# Generated by Django 4.1.5 on 2024-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=500, null=True)),
                ('contenido', models.TextField(default='', verbose_name='contenido')),
                ('fuente', models.CharField(max_length=900, null=True)),
                ('fecha', models.DateTimeField(null=True, verbose_name='fecha')),
                ('icon', models.IntegerField(null=True, verbose_name='icon')),
                ('rrss', models.CharField(choices=[('LN', 'Linkedin'), ('X', 'X'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('BG', 'Blog')], max_length=3)),
                ('revisar', models.BooleanField(default=False, verbose_name='revisar')),
                ('publicado', models.BooleanField(default=False, verbose_name='publicado')),
            ],
        ),
    ]
