# Generated by Django 4.1.5 on 2024-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_rrss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tema',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
