# Generated by Django 4.1.5 on 2024-02-22 18:31

import bot_rrss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_rrss', '0002_post_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=bot_rrss.models.upload_to),
        ),
    ]
