# Generated by Django 4.1.5 on 2024-03-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_rrss', '0003_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=60, null=True)),
                ('texto', models.CharField(max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('RSS', 'rss'), ('HTML', 'html')], max_length=4)),
                ('url', models.URLField(verbose_name='url')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=300, null=True)),
                ('publicado', models.DateField(null=True)),
                ('titulo', models.CharField(max_length=300, null=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_rrss.fuentes')),
            ],
        ),
    ]
