# Generated by Django 4.1.5 on 2024-03-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_rrss', '0004_fuentes_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='enlace',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
