# Generated by Django 4.1.5 on 2024-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_rrss', '0005_alter_contenido_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='enlace',
            field=models.URLField(null=True, unique=True),
        ),
    ]
